ore-detection-settings:
  distance: 5
  particle-count: 5
  volume: 0.1
  sounds:
    COAL_ORE: BLOCK_STONE_HIT
    IRON_ORE: BLOCK_ANVIL_HIT
    GOLD_ORE: BLOCK_BELL_USE
    REDSTONE_ORE: BLOCK_NOTE_BLOCK_HARP
    LAPIS_ORE: BLOCK_NOTE_BLOCK_BASS
    DIAMOND_ORE: BLOCK_NOTE_BLOCK_CHIME
    EMERALD_ORE: BLOCK_NOTE_BLOCK_FLUTE
    NETHER_QUARTZ_ORE: BLOCK_LAVA_POP
    COPPER_ORE: BLOCK_NOTE_BLOCK_BANJO
    NETHER_GOLD_ORE: BLOCK_GOLD_BLOCK_HIT
    ANCIENT_DEBRIS: BLOCK_NETHER_BRICKS_HIT
    DEEPSLATE_COAL_ORE: BLOCK_STONE_HIT
    DEEPSLATE_IRON_ORE: BLOCK_ANVIL_HIT
    DEEPSLATE_COPPER_ORE: BLOCK_NOTE_BLOCK_BANJO
    DEEPSLATE_GOLD_ORE: BLOCK_GOLD_BLOCK_HIT
    DEEPSLATE_REDSTONE_ORE: BLOCK_NOTE_BLOCK_HARP
    DEEPSLATE_EMERALD_ORE: BLOCK_NOTE_BLOCK_FLUTE
    DEEPSLATE_LAPIS_ORE: BLOCK_NOTE_BLOCK_BASS
    DEEPSLATE_DIAMOND_ORE: BLOCK_NOTE_BLOCK_CHIME
  particles:
    COAL_ORE: SMOKE_NORMAL
    IRON_ORE: FALLING_DUST
    GOLD_ORE: REDSTONE
    REDSTONE_ORE: REDSTONE
    LAPIS_ORE: WATER_DROP
    DIAMOND_ORE: ENCHANTMENT_TABLE
    EMERALD_ORE: VILLAGER_HAPPY
    NETHER_QUARTZ_ORE: NETHER_STAR
    COPPER_ORE: CAMPFIRE_COSY_SMOKE
    NETHER_GOLD_ORE: GLOW
    ANCIENT_DEBRIS: DRAGON_BREATH
    DEEPSLATE_COAL_ORE: SMOKE_NORMAL
    DEEPSLATE_IRON_ORE: FALLING_DUST
    DEEPSLATE_COPPER_ORE: CAMPFIRE_COSY_SMOKE
    DEEPSLATE_GOLD_ORE: TOTEM_OF_UNDYING
    DEEPSLATE_REDSTONE_ORE: REDSTONE
    DEEPSLATE_EMERALD_ORE: VILLAGER_HAPPY
    DEEPSLATE_LAPIS_ORE: WATER_DROP
    DEEPSLATE_DIAMOND_ORE: ENCHANTMENT_TABLE
  color:
    GOLD_ORE:
      r: 255
      g: 255
      b: 0

ore-names:
  DIAMOND_ORE: 'Sparkling Diamond'
  IRON_ORE: 'Shiny Iron'
  # ... and so on for other ores

message: "%ore_name% is %grid_range% blocks away"

compass-gui-title: "Toggle Ore Detection"
compass-item-name: "Ore Detector"
