name: OreDetectorPlugin
main: org.plugin.oredetectorplugin.OreDetectorPlugin
version: 1.2
author: YourName
commands:
  reloadconfig:
    description: Reloads the OreDetectorPlugin configuration.
    usage: /reloadconfig
    permission: oredetector.reloadconfig
    default: op

    permissions:
      oredetector.reloadconfig:
        description: Allows the player to reload the OreDetectorPlugin configuration.
        default: op
        oredetector.use:
          description: Allows the player to use the Ore Detector
          default: true