name: OreDetectorPlugin
main: org.plugin.oredetectorplugin.OreDetectorPlugin
version: 1.5
author: Gblack
api-version: 1.16
commands:
  oreconfigreload:
    description: Reload the OreDetectorPlugin config
    usage: /<command>
    aliases: [oreconfigr, oreload]
    permission: oredetectorplugin.reload

permissions:
     oredetector.use:
       description: Allows the player to use the Ore Detector
       default: true