name: OreDetectorPlugin
main: org.plugin.oredetectorplugin.OreDetectorPlugin
version: 2.0
author: Gblack
api-version: 1.16
commands:
  oreconfigreload:
    description: Reload the OreDetectorPlugin config
    usage: /<command>
    aliases: [oreconfigr, oreload]
    permission: oredetectorplugin.reload

permissions:
  ore-detector.use:
    description: Allows the player to use the Ore Detector compass.
    default: true
  ore-detector.craft:
    description: Allows the player to craft the Ore Detector compass.
    default: true